name: Build

on:
  - push

jobs:
  Build_Clang:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019
          - ubuntu-20.04
          - macOS-10.15
    steps:
    # Install Dependencies
    - name: Windows Dependencies
      if: startsWith(matrix.os,'windows')
      shell: pwsh
      run: |
        echo "Clang (Visual Studio) is already included in the image"
        $clpath = vswhere -products * -latest -prerelease -find **/Hostx64/x64/*   # for x64
        [Environment]::SetEnvironmentVariable("Path", $env:Path + ";$clpath", "User")
        $clangpath = vswhere -products * -latest -prerelease -find **/Llvm/bin/*
        [Environment]::SetEnvironmentVariable("Path", $env:Path + ";$clangpath", "User")
        $vcvarsallpath = vswhere -products * -latest -prerelease -find **/Auxiliary/Build/*
        [Environment]::SetEnvironmentVariable("Path", $env:Path + ";$vcvarsallpath", "User")
    - name: Windows Setup Visual Studio Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.3.0
      with:
        arch: x64

  Skip:
    if: "contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Skip CI 🚫
        run: echo skip CI
